# Podfile

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target "AppTacToe" do
  inherit! :search_paths

  # ignore all warnings from all pods
  inhibit_all_warnings!
  
  abstract_target 'Tests' do
    target "AppTacToeTests"

    pod 'Quick'
    pod 'Nimble'
  end
end
